version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
      - npm install --save-dev jest-junit

  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      - npm run 
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production

reports:
  jest_reports:
    files:
      - "reports/unit/*.xml"
    file-format: JUNITXML
    base-directory: reports/unit

      
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml
